### ISSUE TITLE
Write callbacks

### ISSUE THREAD

**Issue by radupopescu** [zargony/rust-fuse#103]
Hi,

Thanks for making and maintaining `rust-fuse`! The library fills a very important slot in the ecosystem.

I'm currently trying to implement the write support for my file system but there is something that I don't understand. I am working on macOS 10.13.

If I issue an append command:
```
$ echo "test" >> my_file.txt
```
where `my_file.txt` is an existing, non-empty file in my file system, I see that the file will be opened with flags `O_WRONLY`. I don't see `O_APPEND` being passed. Is that correct?

The call to `open` is followed by a call to `write` with offset 0.

I was expecting either `O_APPEND` being passed to `open` and then `write` being done at offset 0, or `O_APPEND` isn't passed, and then `write` is done with offset equal to the current length of the file.

I found some documentation about writeback caches on Linux, where the append mode is handled by the kernel, but no reference to this on macOS.

Do you have any ideas about this issue? It's entirely possible that I'm misunderstanding all the calls.

Thanks!

**Comment by zargony** [comment]
Hi,
thanks for the kind words! Unfortunately, it's been some time that I worked with FUSE and I'm not sure about opening flags myself anymore. I probably would expect it to be similar to what you describe. But if it's different, this is most probably not related to rust-fuse, since rust-fuse only forwards information between the FUSE kernel driver and a useful userspace interface. People of the OSXFUSE community should know a good answer on this I suppose.

**Comment by radupopescu** [comment]
Hi,

Sorry for the delayed reply. I wanted to do some tests before replying.

Indeed, I see that my code is working as expected on Linux, with libfuse 2.9.4. The problem exists solely with OSXFUSE. It seems that a relevant bug was fixed in FreeBSD, too:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220185

This issue was reported for OSXFUSE, but was closed. Let's see what can be done there:
https://github.com/osxfuse/osxfuse/issues/398

From my point of view, this issue can be closed here.

Thanks again!

**Comment by zargony** [comment]
Thanks for making inquiries and for linking the related issues here.

**Comment by radupopescu** [comment]
Unfortunately, I may have spoken too soon.

After some more tests, I see that writing works correctly with the standard `fusexml_fh` C example on Linux, Mac and FreeBSD.

In my own FS, written in Rust using `rust-fuse`, writing works correctly on Linux and FreeBSD, but still fails on macOS (OSXFUSE).

I guess there must be a problem in the way the the user-space part of `rust-fuse` interacts with the OSXFUSE kernel module. I have to investigate further and will open a new ticket, if needed.

Cheers!

**Comment by radupopescu** [comment]
Finally, I found the cause of the problem. It was a misuse of the `flags` argument passed into the `open` callback and back out in the call to `reply.opened(...)`.

Basically I was forwarding the flags in between the two. When a file was opened with `O_WRONLY` (==0x1), passing these flags to the reply meant that `FOPEN_DIRECT_IO` was set for the opened file, causing the incorrect write. That is also why this problem never manifested when opening files in read mode.
