### ISSUE TITLE
FileAttr should implement Default

### ISSUE THREAD

**Issue by bertptrs** [zargony/rust-fuse#112]
As it is, the `FileAttr` struct has a lot of attributes, many of which do not make sense in all file systems. For fat, for example, one might end up specifying less than half of the properties.

When the struct implements `Default`, we can greatly reduce this cruft by specifiying only the properties we care about, and having a sensible default for any others.

As a suggestion, one might have the following defaults:

- ino: 0,
- atime: unix epoch,
- ctime: unix epoch,
- crtime: unix epoch,
- mtime: unix epoch,
- size: 0,
- blocks: 0,
- perm: `0o777`,
- kind: fuse::FileType::File,
- nlink: 1,
- uid: 0,
- gid: 0,
- rdev: 0,
- flags: 0

Not all of these will make as much sense, but then again those are the ones everyone should override.

**Comment by wfraser** [comment]
Disagree. A type shouldn't implement Default unless all the fields' default values make sense, which is going to be highly filesystem specific.

**Comment by zargony** [comment]
Thanks for the proposal, but I also disagree. These defaults may be convenient in some cases but there's no reasonable default for a complete new inode (especially when it comes to the inode number)
