### ISSUE TITLE
Set up CI to run tests on FreeBSD

### ISSUE THREAD

**Issue by zargony** [zargony/rust-fuse#128]
Since rust-fuse works with FreeBSD, we should run CI tests for FreeBSD as well.

/ping @asomers Does Travis CI support this somehow or do we need a different CI provider? Since Rust itself seems to move away from Travis, I was thinking about having a look at Azure pipelines.

**Comment by asomers** [comment]
Travis doesn't do it.  We need Cirrus-CI, which can either coexist with Travis or completely replace it.  Follow the instructions at https://cirrus-ci.org/guide/quick-start/ up to "post-installation", then ping me and I'll submit a PR for the rest.

**Comment by zargony** [comment]
I tried Azure Pipelines as well. It's more complex than Travis but works well (MacOS jobs on Travis are failing often lately). They don't have FreeBSD support yet though (well, their CI runner basically works on FreeBSD but they don't have free FreeBSD runners (yet?)). I'll keep Azure in a PR for now.

Cirrus CI is connected to this repo now. Feel free to create a config.

If you have a free minute, could you have a look at the README as well? I added short descriptions on how to install fuse and pkg-config for Linux and Mac, but I didn't know the exact commands / names for FreeBSD.
