### ISSUE TITLE
fuse_attr needs blksize

### ISSUE THREAD

**Issue by akiradeveloper** [zargony/rust-fuse#38]
Current rust-fuse doesn't have blksize field in fuse_attr struct.

Is this a bug?

``` c
struct fuse_attr {
        __u64   ino;
        __u64   size;
        __u64   blocks;
        __u64   atime;
        __u64   mtime;
        __u64   ctime;
        __u32   atimensec;
        __u32   mtimensec;
        __u32   ctimensec;
        __u32   mode;
        __u32   nlink;
        __u32   uid;
        __u32   gid;
        __u32   rdev;
        __u32   blksize;
        __u32   padding;
};
```

**Comment by cuviper** [comment]
Well, rust-fuse declares itself using protocol 7.8 (`FUSE_KERNEL_VERSION` and `FUSE_KERNEL_MINOR_VERSION`), but Linux only added `blksize` starting in protocol 7.9 with [commit 0e9663ee452ff](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=0e9663ee452ffce0d429656ebbcfe69417a30e92&context=5&ignorews=0&dt=0), released in Linux 2.6.24.  I'm not sure what OSX has.

**Comment by akiradeveloper** [comment]
I see. So that's not a bug. But, being adherent to that old version sounds no good to users.

**Comment by akiradeveloper** [comment]
But supporting 7.8 protocol sounds reasonable if you construct a simple fuse binding.
Yeah, my nim-fuse will follow you.

**Comment by zargony** [comment]
Release 2.7.4 of OSXFUSE seems to be at protocol version 7.8: [[header](https://github.com/osxfuse/kext/blob/osxfuse-2/fuse_kernel.h#L46)]
The master branch however seems to have unreleased stuff for protocol version up to 7.19: [[header](https://github.com/osxfuse/kext/blob/master/fuse_kernel.h#L119)]

**Comment by kahing** [comment]
I wonder if it's because of protocol versions that `-o atomic_o_trunc` also doesn't work?

**Comment by zargony** [comment]
fuse_attr.blksize and FUSE_ATOMIC_O_TRUNC were both introduced in 7.9, we're still using 7.8 unfortunately.
I started to work on supporting a newer protocol in PR #97. It's targeting protocol 7.19 which seems to be well supported by Linux and macOS.
