### ISSUE TITLE
Linux umount() is only permitted for root

### ISSUE THREAD

**Issue by cuviper** [zargony/rust-fuse#43]
After commits ef283a7c8980657a388f162bc65895ba429db0d6 and e9560fda914ec9840409b2db973b7dfcf2f3eae8, Linux builds are no longer using the FUSE unmount library call, only the umount syscall.  However, this only works for root, and other users get EPERM.

The FUSE library handles this failure by running `fusermount`, which is setuid-root, just like it does for mounting in the first place.

Thus non-root users can't use drop or variable scopes to unmount a session from spawn_mount anymore.

**Comment by zargony** [comment]
Ouch, I wasn't aware of that. So that's a good reason to still use `fuse_unmount_compat22` on Linux I guess
