### ISSUE TITLE
Add details about dependencies (install instructions) to README

### ISSUE THREAD

**Issue by waynenilsen** [zargony/rust-fuse#54]
I am trying to build this from the repo on Ubuntu 15.04 and having some trouble, I was hoping that you could point me in the right direction. I have fuse installed `fuse is already the newest version.` but there seems to be something in the build script that is triggering a build failure. I tracked it down to the fact that the program below has the output that it does. But I have fuse installed, so I'm not sure where to go from here.

```
$ pkg-config --libs --cflags libfuse
Package libfuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `libfuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libfuse' found
```

For now, I commented out the build script in `Cargo.toml` and it builds just fine. I'm not sure how to proceed from here but just wanted to let you know that I ran into this problem on my machine.

**Comment by kellen** [comment]
You need the dev package for libfuse: `sudo apt-get install pkg-config fuse libfuse-dev`

**Comment by skylerberg** [comment]
Should this be documented in the readme?

**Comment by zargony** [comment]
I think this has improved over time and can be closed now.
