### ISSUE TITLE
Support for latest OXS fuse version - 3.3.2

### ISSUE THREAD

**Issue by korczis** [zargony/rust-fuse#65]
It seems rust-fuse is not working with latest OSX fuse version [3.3.2](https://osxfuse.github.io/2016/05/26/OSXFUSE-3.3.2.html)

Please add support for latest version ...

**Comment by zargony** [comment]
I just tried osxfuse 3.5.0 on a clean macOS 10.12 and had no problems. Only thing I needed to install besides osxfuse itself was pkg-config (which indeed should be documented, see #54). Could you be more specific about why it fails for you?

**Comment by zargony** [comment]
Closing this, since it works fine here (tried again on a fresh machine, fuse 3.5.2). Feel free to reopen with a more detailed problem description.
