### ISSUE TITLE
How to programmatically flush OSX FUSE Cache?

### ISSUE THREAD

**Issue by korczis** [zargony/rust-fuse#66]
Please document how the OSX Fuse Cache can be flushed programatically.

**Comment by zargony** [comment]
Which cache exactly are you talking about? Afaik, neither Rust-FUSE nor the FUSE kernel driver contains a caching mechanism.

"Front end" inode access (from kernel to the fs) is cached by the kernel for up to the ttl you reply with in the `lookup` implementation. The cache details depend on the kernel (Linux, BSD, Darwin. However I agree that this return value could be documented better in Rust-FUSE).

On the "back end" side, the underlaying device usually caches on a block-level basis (e.g. by the hard drive). This caching mechanism is left to the filesystem implementation or lower levels.

From the user side of a filesystem, the kernel usually provides system calls to trigger cache flushing, i.e. the fflush(3) function in libc.
