### ISSUE TITLE
Package fuse was not found in the pkg-config search path

### ISSUE THREAD

**Issue by aidan-fitz** [zargony/rust-fuse#69]
I'm trying to build a FUSE project on Linux and I get this error:
```
   Compiling fuse v0.2.8
failed to run custom build command for `fuse v0.2.8`
Process didn't exit successfully: `/home/aidan/hashtag-fs/target/debug/build/fuse-eb6a62fe8373dd63/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package fuse was not found in the pkg-config search path.\nPerhaps you should add the directory containing `fuse.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'fuse\' found\n" } }', src/libcore/result.rs:688
```

It looks like it's because the library isn't being downloaded normally, which is weird because it's on crates.io. What's going on?

**Comment by cuviper** [comment]
You need to install the system's fuse development package, because
rust-fuse does use a little of the C fuse library.

**Comment by aidan-fitz** [comment]
Ah, thanks. On Ubuntu the package name is `libfuse-dev`.

Is this in the README? If not, can you add it?

**Comment by cuviper** [comment]
Hmm, I suppose you're right, there's no mention in the README, but in #55 @zargony indicated this might be appropriate to add.  Would you like to send a PR for this?

**Comment by cuviper** [comment]
Let's leave it to #54 to track this.
