### ISSUE TITLE
Read is single threaded

### ISSUE THREAD

**Issue by yaitskov** [zargony/rust-fuse#70]
First read hangs for 6 seconds and second read is not executed until first read is complete.
```

    fn read(&mut self, _req: &Request, ino: u64, _: u64,
            offset: u64, size: u32, reply: ReplyData) {
        println!("read ino {}; ofs {}; sz {}", ino, offset, size);
        self.counter += 1;
        if self.counter % 2 == 1 {
            sleep(Duration::new(6, 0))
        }

```

**Comment by cuviper** [comment]
If you want this to be completed asynchronously, you should send this
request to your own separate thread. It can't generally make any threading
assumptions for you...

**Comment by yaitskov** [comment]
Thanks,

I haven't realized that Filesystem callback method doesn't return value and I can call reply.ok() after returning flow control.
