### ISSUE TITLE
getattr does not receive fh

### ISSUE THREAD

**Issue by amosonn** [zargony/rust-fuse#82]
In the c libfuse, `getattr` calls receive `fh` if there is some (see fuse_lowlevel.c:1087, `static void do_getattr`). In rust-fuse, only `setattr` receives `_fh: Option<u64>`.

**Comment by zargony** [comment]
That's because rust-fuse still uses the FUSE kernel ABI version 7.6 and `fh` in `getattr` was introduced in 7.9. We definitely need to add support for newer versions, but it's hard to support a range of versions and it's not unclear yet how rust-fuse should handle it (see also #83).

**Comment by zargony** [comment]
Getattr calls will receive fh after we switched to a newer FUSE kernel ABI in #97
