### ISSUE TITLE
ReadDirAll

### ISSUE THREAD

**Issue by dweidenfeld** [zargony/rust-fuse#94]
Hi,

why is it not possible to return just all files/folders when a readdir() request comes in?

It seems that many files are missing if I just return everything I know.

regards,
Dom

**Comment by zargony** [comment]
Hi Dom,

that's the way a filesystem is designed in the FUSE world (which matches how the Linux kernel works afaik). It can become very inefficient to always return a full list of files/folders, (e.g. if there are thousands of files), so the kernel needs a way to query a subset. The FUSE interface implements this by giving an offset to readdir and limiting the number of entries in the reply (you can see this like offset and length of a pagination).
Support for building a directory reply could be improved though, e.g. we could try to make it possible to build directory replies from various kinds of iterators.
