### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by ERnsTL** [zargony/rust-fuse#98]
Greetings, there is a project, which presents a higher-level abstraction over rust-fuse: [fuse-mt](https://github.com/wfraser/fuse-mt).

The author currently special-cases the socket type (used for UNIX sockets), because the feature is present in your repository, but not correctly tagged and therefore not present in the crates.io version.

Here is the link to the issue over there: [fuse-mt issue 18](https://github.com/wfraser/fuse-mt/issues/18#issuecomment-337379986)

Any way to solve this? Tag and release a new version?

**Comment by zargony** [comment]
Weird. I have no idea how the wrong tagging happened. I just released 0.3.1 which should be ok again.
